[pytest]
testpaths =
    autocal/tests
    tests/python
norecursedirs =
    .git
    node_modules
    dist
    dist-hangprinter-org
    RRF
    klipper
    hangprinter-org
    hp-sim
    slideprinter
    examples
    public
    run
    specs
    debug_sessions
    debug_plots
    plots
