import numpy as np
import math
from cable_joints import vector2 as v2_helpers
from cable_joints.ecs import (
    VelocityComponent, RadiusComponent, MassComponent,
    AngularVelocityComponent, MomentOfInertiaComponent, CoefficientOfFrictionComponent,
    ObstaclePushComponent
)

class BallObstacleBumpSystem:
    """
    This system applies a velocity-based "bump" to balls that have just
    collided with specific obstacles. It runs AFTER the PBD position solve
    and velocity updates. It relies on contact information generated by
    PBDBallObstacleCollisions.
    """
    run_in_pause = False

    def update(self, world, dt):
        contacts = world.get_resource('ball_obstacle_contacts')
        if not contacts:
            return

        for contact in contacts:
            ball_id = contact['ball_id']
            obs_id = contact['obs_id']
            direction = contact['direction'] # This is the normal from obstacle center to ball center

            # Get all required components
            v1_comp = world.get_component(ball_id, VelocityComponent)
            r1_comp = world.get_component(ball_id, RadiusComponent)
            ball_mass_comp = world.get_component(ball_id, MassComponent)
            ball_ang_vel_comp = world.get_component(ball_id, AngularVelocityComponent)
            ball_moi_comp = world.get_component(ball_id, MomentOfInertiaComponent)

            r2_comp = world.get_component(obs_id, RadiusComponent)
            push_comp = world.get_component(obs_id, ObstaclePushComponent)
            obs_ang_vel_comp = world.get_component(obs_id, AngularVelocityComponent)
            obs_moi_comp = world.get_component(obs_id, MomentOfInertiaComponent)
            obs_friction_comp = world.get_component(obs_id, CoefficientOfFrictionComponent)

            # Ensure all components are present before proceeding
            if not all([v1_comp, r1_comp, ball_mass_comp, r2_comp, push_comp]):
                continue

            v1 = v1_comp.vel
            r1 = r1_comp.radius
            r2 = r2_comp.radius
            push_vel = push_comp.pushVel

            omega_obs = obs_ang_vel_comp.angular_velocity if obs_ang_vel_comp else 0.0
            mu = obs_friction_comp.mu if obs_friction_comp else 0.0
            omega_ball = ball_ang_vel_comp.angular_velocity if ball_ang_vel_comp else 0.0

            tangent = np.array([-direction[1], direction[0], 0.0])

            # Obstacle surface velocity at contact point
            v_surf_obs_tangential_comp = 0
            if omega_obs != 0:
                # v_surf = omega_obs x r_obs, where r_obs = direction * r2
                v_surf_x = -omega_obs * direction[1] * r2
                v_surf_y =  omega_obs * direction[0] * r2
                v_surf_obs_tangential_comp = v_surf_x * tangent[0] + v_surf_y * tangent[1]

            # Ball surface velocity at contact point
            # v_contact_ball = v_ball + (omega_ball x r_ball), where r_ball = -direction * r1
            r_contact_ball = -direction * r1
            v_angular_ball_at_contact = np.cross(np.array([0, 0, omega_ball]), r_contact_ball)
            v_ball_at_contact = v1 + v_angular_ball_at_contact
            v_ball_tangential_comp = np.dot(v_ball_at_contact, tangent)

            v_rel_tangential = v_ball_tangential_comp - v_surf_obs_tangential_comp

            s_sign = 0
            # Friction opposes relative motion
            if abs(v_rel_tangential) > 1e-9 and mu != 0:
                s_sign = -math.copysign(1, v_rel_tangential)

            effective_push_dir = direction.copy()
            if s_sign != 0:
                effective_push_dir += tangent * (mu * s_sign)
            v2_helpers.normalize_inplace(effective_push_dir)

            v1 += effective_push_dir * push_vel

            if mu > 0 and ball_mass_comp:
                delta_v_ball_tangential_actual_scalar_comp = np.dot(effective_push_dir, tangent) * push_vel

                if abs(delta_v_ball_tangential_actual_scalar_comp) > 1e-9:
                    j_t_on_ball_vec = tangent * (delta_v_ball_tangential_actual_scalar_comp * ball_mass_comp.mass)

                    if ball_ang_vel_comp and ball_moi_comp and ball_moi_comp.inv_inertia > 0:
                        r_contact_ball = direction * -r1
                        delta_l_ball = r_contact_ball[0] * j_t_on_ball_vec[1] - r_contact_ball[1] * j_t_on_ball_vec[0]
                        ball_ang_vel_comp.angular_velocity += delta_l_ball * ball_moi_comp.inv_inertia

                    if obs_ang_vel_comp and obs_moi_comp and obs_moi_comp.inv_inertia > 0:
                        j_t_on_obs_vec = j_t_on_ball_vec * -1
                        r_contact_obs = direction * r2
                        delta_l_obs = r_contact_obs[0] * j_t_on_obs_vec[1] - r_contact_obs[1] * j_t_on_obs_vec[0]
                        obs_ang_vel_comp.angular_velocity += delta_l_obs * obs_moi_comp.inv_inertia
