# Sticky + Compact Binary Schema:
# We define a Block. Groups of rows sharing the same context (Cols 2-5) are combined.
# We use "Sticky" headers (only writing changed context) and variable-width values.
# We read columns from the csv file generated by rrf_simulator (the LogMotion output).

# 1. Block Header (Variable Size: 2 to 22 Bytes)
# | Offset | Type   | Description                                                         |
# | :---   | :---   | :---                                                                |
# |      0 | Uint8  | Change Mask (Bit 0: Time, Bit 1: Col3, Bit 2: Col4, Bit 3: Col5)    |
# |      1 | Uint8  | Count (N): How many items follow in this block?                     |
# |   2... | Var    | Conditional Fields (Only present if corresponding Bit in Mask is 1) |
# |        |        | - If Bit 0 set: Uint64 (8 bytes)                                    |
# |        |        | - If Bit 1 set: Int32  (4 bytes)                                    |
# |        |        | - If Bit 2 set: Int32  (4 bytes)                                    |
# |        |        | - If Bit 3 set: Int32  (4 bytes)                                    |

# 2. Block Body (Repeated N times - Variable Size: 2 to 5 Bytes each)
# | Offset | Type   | Description                                                         |
# | :---   | :---   | :---                                                                |
# |      0 | Uint8  | Bits 0-5: CAN ID (Max 63)                                           |
# |        |        | Bits 6-7: Type Code (Determines payload size)                       |
# |   1... | Var    | Column 6 Value (Size depends on Type Code)                          |

# Type Codes (Bits 6-7 of Body Byte 0):
# | Code | Binary | Data Type | Payload Size | Total Item Size |
# | :--- | :---   | :---      | :---         | :---            |
# |    0 | 00     | Int8      | 1 Byte       | 2 Bytes         |
# |    1 | 01     | Int16     | 2 Bytes      | 3 Bytes         |
# |    2 | 10     | Int32     | 4 Bytes      | 5 Bytes         |
# |    3 | 11     | Float32   | 4 Bytes      | 5 Bytes         |


import sys
import csv
import struct
import os

def convert_csv_to_highly_compressed(input_path):
    output_path = os.path.splitext(input_path)[0] + '.can'

    print(f"Processing {input_path}...")

    with open(input_path, 'r') as f_in, open(output_path, 'wb') as f_out:
        # Check for JSON header
        pos = f_in.tell()
        if not f_in.readline().strip().startswith('{'):
            f_in.seek(pos)

        csv_reader = csv.reader(f_in)

        # State tracking for "Sticky" compression
        prev_c2 = None
        prev_c3 = None
        prev_c4 = None
        prev_c5 = None

        # Buffer for current group
        current_group_key = None # (c2, c3, c4, c5)
        group_buffer = [] # list of (id, value_string)

        def flush_group():
            nonlocal prev_c2, prev_c3, prev_c4, prev_c5
            nonlocal current_group_key, group_buffer

            if not group_buffer:
                return

            c2, c3, c4, c5 = current_group_key

            # --- 1. Build Header with Bitmask ---
            mask = 0
            header_payload = bytearray()

            # Bit 0: Col2 (Time) - Uint64
            if c2 != prev_c2:
                mask |= 1
                header_payload.extend(struct.pack('<Q', c2))
                prev_c2 = c2

            # Bit 1: Col3 - Int32
            if c3 != prev_c3:
                mask |= 2
                header_payload.extend(struct.pack('<i', c3))
                prev_c3 = c3

            # Bit 2: Col4 - Int32
            if c4 != prev_c4:
                mask |= 4
                header_payload.extend(struct.pack('<i', c4))
                prev_c4 = c4

            # Bit 3: Col5 - Int32
            if c5 != prev_c5:
                mask |= 8
                header_payload.extend(struct.pack('<i', c5))
                prev_c5 = c5

            # Write Mask and Count
            count = len(group_buffer)
            f_out.write(struct.pack('<BB', mask, count))
            # Write the variable header fields
            f_out.write(header_payload)

            # --- 2. Write Body Items with Variable Width ---
            for (can_id, val_str) in group_buffer:
                can_id = int(can_id)

                # Determine Type and pack
                if '.' in val_str:
                    # Float32 -> Type 11 (0x3)
                    val = float(val_str)
                    type_bits = 3
                    # Header byte: (Type << 6) | (ID & 0x3F)
                    header_byte = (type_bits << 6) | (can_id & 0x3F)
                    f_out.write(struct.pack('<Bf', header_byte, val))
                else:
                    val = int(val_str)
                    # Check range for integer compression
                    if -128 <= val <= 127:
                        # Int8 -> Type 00 (0x0)
                        type_bits = 0
                        header_byte = (type_bits << 6) | (can_id & 0x3F)
                        f_out.write(struct.pack('<Bb', header_byte, val))
                    elif -32768 <= val <= 32767:
                        # Int16 -> Type 01 (0x1)
                        type_bits = 1
                        header_byte = (type_bits << 6) | (can_id & 0x3F)
                        f_out.write(struct.pack('<Bh', header_byte, val))
                    else:
                        # Int32 -> Type 10 (0x2)
                        type_bits = 2
                        header_byte = (type_bits << 6) | (can_id & 0x3F)
                        f_out.write(struct.pack('<Bi', header_byte, val))

        # --- Main Loop ---
        expected_idx = 0
        for row in csv_reader:
            if not row: continue

            # Validation
            if int(row[0]) != expected_idx:
                raise ValueError(f"Index mismatch at {expected_idx}")
            expected_idx += 1

            # Extract keys
            c2, c3, c4, c5 = int(row[2]), int(row[3]), int(row[4]), int(row[5])
            row_key = (c2, c3, c4, c5)

            if (row_key != current_group_key) or (len(group_buffer) >= 255):
                flush_group()
                current_group_key = row_key
                group_buffer = []

            group_buffer.append((row[1], row[6]))

        flush_group()

    print(f"Success! Saved to {output_path}")

if __name__ == "__main__":
    convert_csv_to_highly_compressed(sys.argv[1])
