#pragma once

// Centralised feature overrides for x86_64 host builds.

#ifdef HAS_LWIP_NETWORKING
#undef HAS_LWIP_NETWORKING
#endif
#define HAS_LWIP_NETWORKING 0

#ifdef HAS_WIFI_NETWORKING
#undef HAS_WIFI_NETWORKING
#endif
#define HAS_WIFI_NETWORKING 0

#ifdef HAS_W5500_NETWORKING
#undef HAS_W5500_NETWORKING
#endif
#define HAS_W5500_NETWORKING 0

#ifdef HAS_RTOSPLUSTCP_NETWORKING
#undef HAS_RTOSPLUSTCP_NETWORKING
#endif
#define HAS_RTOSPLUSTCP_NETWORKING 0

#ifdef HAS_ESP32_NETWORKING
#undef HAS_ESP32_NETWORKING
#endif
#define HAS_ESP32_NETWORKING 0

#ifdef HAS_HOST_NETWORKING
#undef HAS_HOST_NETWORKING
#endif
#define HAS_HOST_NETWORKING 1

#ifdef HAS_NETWORKING
#undef HAS_NETWORKING
#endif
#define HAS_NETWORKING HAS_HOST_NETWORKING

#ifdef HAS_CPU_TEMP_SENSOR
#undef HAS_CPU_TEMP_SENSOR
#endif
#define HAS_CPU_TEMP_SENSOR 0

#ifdef HAS_HIGH_SPEED_SD
#undef HAS_HIGH_SPEED_SD
#endif
#define HAS_HIGH_SPEED_SD 0

#ifdef HAS_MASS_STORAGE
#undef HAS_MASS_STORAGE
#endif
#define HAS_MASS_STORAGE 1

#ifdef HAS_SBC_INTERFACE
#undef HAS_SBC_INTERFACE
#endif
#define HAS_SBC_INTERFACE 0

#ifdef HAS_EMBEDDED_FILES
#undef HAS_EMBEDDED_FILES
#endif
#define HAS_EMBEDDED_FILES 0

#ifdef SUPPORT_LED_STRIPS
#undef SUPPORT_LED_STRIPS
#endif
#define SUPPORT_LED_STRIPS 0

#ifdef SUPPORT_DMA_DOTSTAR
#undef SUPPORT_DMA_DOTSTAR
#endif
#define SUPPORT_DMA_DOTSTAR 0

#ifdef SUPPORT_DMA_NEOPIXEL
#undef SUPPORT_DMA_NEOPIXEL
#endif
#define SUPPORT_DMA_NEOPIXEL 0

#ifdef SUPPORT_LASER
#undef SUPPORT_LASER
#endif
#define SUPPORT_LASER 0

#ifdef SUPPORT_SCANNING_PROBES
#undef SUPPORT_SCANNING_PROBES
#endif
#define SUPPORT_SCANNING_PROBES 0

#ifdef SUPPORT_IOBITS
#undef SUPPORT_IOBITS
#endif
#define SUPPORT_IOBITS 0

#ifdef SUPPORT_REMOTE_COMMANDS
#undef SUPPORT_REMOTE_COMMANDS
#endif
#define SUPPORT_REMOTE_COMMANDS 0

#ifdef SUPPORT_ASYNC_MOVES
#undef SUPPORT_ASYNC_MOVES
#endif
#define SUPPORT_ASYNC_MOVES 0

#ifdef SUPPORT_TMC2660
#undef SUPPORT_TMC2660
#endif
#define SUPPORT_TMC2660 0

#ifdef SUPPORT_TMC22xx
#undef SUPPORT_TMC22xx
#endif
#define SUPPORT_TMC22xx 0

#ifdef SUPPORT_TMC51xx
#undef SUPPORT_TMC51xx
#endif
#define SUPPORT_TMC51xx 0

#ifdef SUPPORT_ACCELEROMETERS
#undef SUPPORT_ACCELEROMETERS
#endif
#define SUPPORT_ACCELEROMETERS 0

#ifdef SUPPORT_PANELDUE_FLASH
#undef SUPPORT_PANELDUE_FLASH
#endif
#define SUPPORT_PANELDUE_FLASH 0

#ifdef SUPPORT_HTTP
#undef SUPPORT_HTTP
#endif
#define SUPPORT_HTTP 1

#ifdef SUPPORT_FTP
#undef SUPPORT_FTP
#endif
#define SUPPORT_FTP 0

#ifdef SUPPORT_TELNET
#undef SUPPORT_TELNET
#endif
#define SUPPORT_TELNET 0

#ifdef SUPPORT_BME280
#undef SUPPORT_BME280
#endif
#define SUPPORT_BME280 0

#ifdef SUPPORT_ADS131A02
#undef SUPPORT_ADS131A02
#endif
#define SUPPORT_ADS131A02 0

#ifdef SUPPORT_CAN_EXPANSION
#undef SUPPORT_CAN_EXPANSION
#endif
#define SUPPORT_CAN_EXPANSION 1

#ifdef SUPPORT_CAN_FD
#undef SUPPORT_CAN_FD
#endif
#define SUPPORT_CAN_FD 1

#ifdef HAS_VREF_MONITOR
#undef HAS_VREF_MONITOR
#endif
#define HAS_VREF_MONITOR 0

#ifdef HAS_12V_MONITOR
#undef HAS_12V_MONITOR
#endif
#define HAS_12V_MONITOR 0

#ifdef HAS_VOLTAGE_MONITOR
#undef HAS_VOLTAGE_MONITOR
#endif
#define HAS_VOLTAGE_MONITOR 0
