import numpy as np

from .ecs import (
    PositionComponent, VelocityComponent, RadiusComponent, MassComponent,
    RestitutionComponent, AngularVelocityComponent,
    MomentOfInertiaComponent, CoefficientOfFrictionComponent
)

class BallBorderVelocityContactSystem:
    """
    Handles the velocity-level response (restitution and friction) for ball-border
    collisions. It runs AFTER the main PBD velocity update and relies on contact
    information generated by PBDBallBorderCollisions.
    """
    run_in_pause = False

    def update(self, world, dt):
        contacts = world.get_resource('ball_border_contacts')
        if not contacts:
            return

        for contact in contacts:
            ball_id = contact['ball_id']
            normal = contact['normal']  # Normal points away from the border towards the ball

            # Get all required components for the ball
            pos_comp = world.get_component(ball_id, PositionComponent)
            vel_comp = world.get_component(ball_id, VelocityComponent)
            radius_comp = world.get_component(ball_id, RadiusComponent)
            mass_comp = world.get_component(ball_id, MassComponent)
            moi_comp = world.get_component(ball_id, MomentOfInertiaComponent)
            ang_vel_comp = world.get_component(ball_id, AngularVelocityComponent)
            restitution_comp = world.get_component(ball_id, RestitutionComponent)
            friction_comp = world.get_component(ball_id, CoefficientOfFrictionComponent)

            # Ensure all necessary components are present
            if not all([pos_comp, vel_comp, radius_comp, mass_comp, moi_comp, ang_vel_comp, restitution_comp]):
                continue

            mass = mass_comp.mass
            inv_mass = 1.0 / mass if mass > 0 else 0.0
            inv_inertia = moi_comp.inv_inertia

            if inv_mass == 0.0 and inv_inertia == 0.0:
                continue

            # Ball properties
            radius = radius_comp.radius
            restitution = restitution_comp.restitution
            mu = friction_comp.mu if friction_comp else 0.0
            ang_vel = ang_vel_comp.angular_velocity

            # Vector from ball center to contact point
            r_ball = -normal * radius

            # Relative velocity at contact point (border is static)
            # v_contact = v_linear + v_angular
            v_angular_at_contact = np.cross(np.array([0, 0, ang_vel]), r_ball)
            v_rel = vel_comp.vel + v_angular_at_contact

            # Decompose relative velocity into normal and tangential components
            v_rel_n_scalar = np.dot(v_rel, normal)

            # If the ball is already moving away from the border, do nothing
            if v_rel_n_scalar >= 0:
                continue

            # --- 1. Restitution (Normal Impulse) ---
            # Calculate generalized inverse mass in the normal direction.
            # This represents how much the contact point accelerates for a given impulse.
            r_cross_n_z = np.cross(r_ball, normal)[2]
            w_inv_n = inv_mass + inv_inertia * (r_cross_n_z ** 2)

            if w_inv_n < 1e-9:
                continue

            # Calculate the magnitude of the impulse needed to achieve the post-collision velocity.
            # v_n_new = -e * v_n_old  => delta_v_n = v_n_new - v_n_old = -(1+e)v_n_old
            j_n = -(1.0 + restitution) * v_rel_n_scalar / w_inv_n

            # Apply the normal impulse
            impulse_n_vec = j_n * normal
            vel_comp.vel += impulse_n_vec * inv_mass
            torque_n_impulse = r_cross_n_z * j_n
            ang_vel_comp.angular_velocity += torque_n_impulse * inv_inertia

            # --- 2. Friction (Tangential Impulse) ---
            # Re-calculate relative velocity after normal impulse to correctly calculate friction
            v_angular_at_contact_new = np.cross(np.array([0, 0, ang_vel_comp.angular_velocity]), r_ball)
            v_rel_new = vel_comp.vel + v_angular_at_contact_new

            v_rel_t_vec = v_rel_new - np.dot(v_rel_new, normal) * normal
            v_rel_t_mag = np.linalg.norm(v_rel_t_vec)

            if mu > 0 and v_rel_t_mag > 1e-9:
                tangent = v_rel_t_vec / v_rel_t_mag

                # Calculate generalized inverse mass in the tangential direction
                r_cross_t_z = np.cross(r_ball, tangent)[2]
                w_inv_t = inv_mass + inv_inertia * (r_cross_t_z ** 2)

                if w_inv_t > 1e-9:
                    # Calculate impulse needed to stop sliding
                    j_t_noslip = -v_rel_t_mag / w_inv_t

                    # Clamp impulse by Coulomb's friction law
                    j_t = np.clip(j_t_noslip, -mu * j_n, mu * j_n)

                    # Apply the tangential impulse
                    impulse_t_vec = j_t * tangent
                    vel_comp.vel += impulse_t_vec * inv_mass
                    torque_t_impulse = r_cross_t_z * j_t
                    ang_vel_comp.angular_velocity += torque_t_impulse * inv_inertia
