import numpy as np

from .ecs import (
    PositionComponent, VelocityComponent, RadiusComponent, MassComponent,
    RestitutionComponent, AngularVelocityComponent,
    MomentOfInertiaComponent, CoefficientOfFrictionComponent,
    FlipperStateComponent, FlipperTipComponent
)

class BallBorderOrFlipperVelocityContactSystem:
    """
    Handles the velocity-level response (restitution and friction) for ball
    collisions with borders and flippers. It runs AFTER the main PBD velocity
    update and relies on contact information generated by the PBD collision systems.
    """
    run_in_pause = False

    def _handle_ball_contact(self, world, ball_id, normal, v_surface, restitution_other, friction_other):
        """
        Generic handler for ball contacts with a surface (static or dynamic).
        Applies impulses for restitution and friction.
        """
        # Get all required components for the ball
        pos_comp = world.get_component(ball_id, PositionComponent)
        vel_comp = world.get_component(ball_id, VelocityComponent)
        radius_comp = world.get_component(ball_id, RadiusComponent)
        mass_comp = world.get_component(ball_id, MassComponent)
        moi_comp = world.get_component(ball_id, MomentOfInertiaComponent)
        ang_vel_comp = world.get_component(ball_id, AngularVelocityComponent)
        restitution_comp = world.get_component(ball_id, RestitutionComponent)
        friction_comp = world.get_component(ball_id, CoefficientOfFrictionComponent)

        # Ensure all necessary components are present
        if not all([pos_comp, vel_comp, radius_comp, mass_comp, moi_comp, ang_vel_comp, restitution_comp]):
            return

        mass = mass_comp.mass
        inv_mass = 1.0 / mass if mass > 0 else 0.0
        inv_inertia = moi_comp.inv_inertia

        if inv_mass == 0.0 and inv_inertia == 0.0:
            return

        # Ball properties
        radius = radius_comp.radius
        restitution_ball = restitution_comp.restitution
        mu_ball = friction_comp.mu if friction_comp else 0.0
        ang_vel = ang_vel_comp.angular_velocity

        # Combine properties of the two colliding objects (e.g., average)
        restitution = (restitution_ball + restitution_other) / 2.0
        mu = (mu_ball + friction_other) / 2.0

        # Vector from ball center to contact point
        r_ball = -normal * radius

        # Ball velocity at contact point
        v_angular_at_contact = np.cross(np.array([0, 0, ang_vel]), r_ball)
        v_ball_at_contact = vel_comp.vel + v_angular_at_contact

        # Relative velocity at contact point
        v_rel = v_ball_at_contact - v_surface

        # Decompose relative velocity into normal and tangential components
        v_rel_n_scalar = np.dot(v_rel, normal)

        # If the ball is already moving away from the surface, do nothing
        if v_rel_n_scalar >= 0:
            return

        # --- 1. Restitution (Normal Impulse) ---
        r_cross_n_z = np.cross(r_ball, normal)[2]
        w_inv_n = inv_mass + inv_inertia * (r_cross_n_z ** 2)

        if w_inv_n < 1e-9:
            return

        j_n = -(1.0 + restitution) * v_rel_n_scalar / w_inv_n

        impulse_n_vec = j_n * normal
        vel_comp.vel += impulse_n_vec * inv_mass
        torque_n_impulse = r_cross_n_z * j_n
        ang_vel_comp.angular_velocity += torque_n_impulse * inv_inertia

        # --- 2. Friction (Tangential Impulse) ---
        # Re-calculate relative velocity after normal impulse
        v_angular_at_contact_new = np.cross(np.array([0, 0, ang_vel_comp.angular_velocity]), r_ball)
        v_ball_at_contact_new = vel_comp.vel + v_angular_at_contact_new
        v_rel_new = v_ball_at_contact_new - v_surface

        v_rel_t_vec = v_rel_new - np.dot(v_rel_new, normal) * normal
        v_rel_t_mag = np.linalg.norm(v_rel_t_vec)

        if mu > 0 and v_rel_t_mag > 1e-9:
            tangent = v_rel_t_vec / v_rel_t_mag
            r_cross_t_z = np.cross(r_ball, tangent)[2]
            w_inv_t = inv_mass + inv_inertia * (r_cross_t_z ** 2)

            if w_inv_t > 1e-9:
                j_t_noslip = -v_rel_t_mag / w_inv_t
                j_t = np.clip(j_t_noslip, -mu * j_n, mu * j_n)
                impulse_t_vec = j_t * tangent
                vel_comp.vel += impulse_t_vec * inv_mass
                torque_t_impulse = r_cross_t_z * j_t
                ang_vel_comp.angular_velocity += torque_t_impulse * inv_inertia

    def update(self, world, dt):
        # --- Handle Border Contacts ---
        border_contacts = world.get_resource('ball_border_contacts')
        if border_contacts:
            for contact in border_contacts:
                # Border is static: v_surface=0, restitution=0, friction=0
                self._handle_ball_contact(world, contact['ball_id'], contact['normal'], np.zeros(3), 0.0, 0.0)

        # --- Handle Flipper Contacts ---
        flipper_contacts = world.get_resource('ball_flipper_contacts')
        if flipper_contacts:
            for contact in flipper_contacts:
                ball_id = contact['ball_id']
                flip_id = contact['flip_id']
                normal = contact['normal']
                contact_point_on_flipper = contact['contact_point_on_flipper']

                # Get flipper components
                flipper_pos_comp = world.get_component(flip_id, PositionComponent)
                flipper_state_comp = world.get_component(flip_id, FlipperStateComponent)
                flipper_restitution_comp = world.get_component(flip_id, RestitutionComponent)

                # Find the associated flipper tip to get its friction component
                flipper_tip_id = None
                tip_entities = world.query([FlipperTipComponent])
                for tip_id in tip_entities:
                    tip_comp = world.get_component(tip_id, FlipperTipComponent)
                    if tip_comp.flipper_entity_id == flip_id:
                        flipper_tip_id = tip_id
                        break
                
                flipper_friction_comp = world.get_component(flipper_tip_id, CoefficientOfFrictionComponent) if flipper_tip_id else None

                if not all([flipper_pos_comp, flipper_state_comp, flipper_restitution_comp]):
                    continue

                # Calculate flipper surface velocity at the contact point
                flipper_pivot_pos = flipper_pos_comp.pos
                flipper_ang_vel = flipper_state_comp.current_angular_velocity
                r_flipper = contact_point_on_flipper - flipper_pivot_pos
                v_flipper = np.cross(np.array([0, 0, flipper_ang_vel]), r_flipper)

                restitution_flipper = flipper_restitution_comp.restitution
                friction_flipper = flipper_friction_comp.mu if flipper_friction_comp else 0.1

                self._handle_ball_contact(world, ball_id, normal, v_flipper, restitution_flipper, friction_flipper)
