#!/usr/bin/env python3
from __future__ import annotations

"""End-to-end debug runner for elliptical feature calibration.

This script is meant to be a one-stop tool to:
1) Inflate a delta dataset to absolute lengths using either a base length or anchors.
2) Fit ellipses (substep 3).
3) Predict theoretical ellipses (substep 4) if anchors available.
4) Optionally solve anchors (substep 5) and re-fit at the solution.
5) Generate a suite of plots (substep 6) plus a plot index with expectations.

Outputs are written into --outdir (default: plots/ellipse_debug/<dataset_stem>).
"""

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from autocal.ellipse_fitting import fit_all_sweeps
from autocal.ellipse_solver import solve_anchors
from autocal.ellipse_visualization import (
    create_calibration_report,
    plot_all_sweeps,
    plot_anchors_2d,
    plot_cost_convergence,
    plot_ellipse_fit,
    plot_residuals_comparison,
    plot_sampling_density,
)
from autocal.theoretical_ellipse import predict_ellipse_coefficients


def _parse_anchors_2d(text: str) -> np.ndarray:
    """Parse anchors from 'x,y;x,y;...' string."""
    points = []
    for pair in text.split(";"):
        pair = pair.strip()
        if not pair:
            continue
        x_str, y_str = pair.split(",")
        points.append([float(x_str), float(y_str)])
    anchors = np.asarray(points, dtype=float)
    if anchors.ndim != 2 or anchors.shape[1] != 2:
        raise ValueError("Expected 2D anchors in 'x,y;x,y;...' format")
    return anchors


def inflate_dataset_to_absolute(
    dataset: dict,
    base_length: Optional[float] = None,
    anchors: Optional[np.ndarray] = None,
) -> dict:
    """Return a deep-copied dataset with absolute lengths."""
    import copy

    abs_data = copy.deepcopy(dataset)
    sweeps_abs = []

    if anchors is None and base_length is None:
        raise ValueError("Provide either --base-length or --anchors to inflate lengths.")

    if anchors is not None:
        baselines = np.linalg.norm(anchors, axis=1)
        for sweep in abs_data.get("sweeps", []):
            fixed_abs = [
                float(baselines[idx] + delta)
                for idx, delta in zip(sweep.get("fixed_anchors", []), sweep.get("fixed_lengths", []))
            ]
            drive_idx = int(sweep["drive_anchor"])
            sensor_idx = int(sweep["sensor_anchor"])
            drive_base = float(baselines[drive_idx])
            sensor_base = float(baselines[sensor_idx])
            points_abs = []
            for p in sweep.get("data_points", []):
                points_abs.append(
                    {
                        **p,
                        "l_drive": float(p["l_drive"] + drive_base),
                        "l_sensor": float(p["l_sensor"] + sensor_base),
                    }
                )
            sweeps_abs.append({**sweep, "fixed_lengths": fixed_abs, "data_points": points_abs})
    else:
        base = float(base_length)
        for sweep in abs_data.get("sweeps", []):
            fixed_abs = [float(fl + base) for fl in sweep.get("fixed_lengths", [])]
            points_abs = []
            for p in sweep.get("data_points", []):
                points_abs.append(
                    {
                        **p,
                        "l_drive": float(p["l_drive"] + base),
                        "l_sensor": float(p["l_sensor"] + base),
                    }
                )
            sweeps_abs.append({**sweep, "fixed_lengths": fixed_abs, "data_points": points_abs})

    abs_data["sweeps"] = sweeps_abs
    return abs_data


def write_plot_index(outdir: Path, entries: List[Tuple[str, str, str]]) -> None:
    """Write a markdown index describing plots, functions, expectations."""
    lines = [
        "# Ellipse Calibration Debug Plots\n",
        "",
        "This folder was generated by `scripts/run_ellipse_calibration_debug.py`.",
        "",
    ]
    for rel_path, functions_text, expect_text in entries:
        lines.extend(
            [
                f"## `{rel_path}`",
                "",
                f"**Functions exercised/validated:** {functions_text}",
                "",
                f"**Expected to see:** {expect_text}",
                "",
            ]
        )
    (outdir / "README_plots.md").write_text("\n".join(lines), encoding="utf-8")


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Run end-to-end ellipse calibration debug.")
    parser.add_argument("dataset", type=Path, help="Sweep dataset JSON (deltas from origin)")
    parser.add_argument(
        "--base-length",
        type=float,
        help="Uniform baseline length to add before fitting (e.g. 1900 for Slideprinter)",
    )
    parser.add_argument(
        "--anchors",
        type=str,
        help="True/guessed 2D anchors as 'x,y;x,y;...'; used to inflate lengths and predict theory.",
    )
    parser.add_argument(
        "--solve",
        action="store_true",
        help="Run substep-5 solver to estimate anchors, then re-fit and plot at solution.",
    )
    parser.add_argument(
        "--method",
        default="SLSQP",
        help="Solver method when --solve (SLSQP or differential_evolution).",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.01,
        help="Sampson RMS threshold for fit validity.",
    )
    parser.add_argument("--min-points", type=int, default=10)
    parser.add_argument(
        "--outdir",
        type=Path,
        default=None,
        help="Output directory. Default: plots/ellipse_debug/<dataset_stem>",
    )
    args = parser.parse_args(argv)

    dataset = json.loads(args.dataset.read_text(encoding="utf-8"))
    anchors_true = _parse_anchors_2d(args.anchors) if args.anchors else None

    outdir = args.outdir or (Path("plots") / "ellipse_debug" / args.dataset.stem)
    outdir.mkdir(parents=True, exist_ok=True)

    plot_entries: List[Tuple[str, str, str]] = []

    # Inflate for Phase-1 QC fits.
    abs_dataset = inflate_dataset_to_absolute(dataset, args.base_length, anchors_true)
    abs_path = outdir / f"{args.dataset.stem}_abs.json"
    abs_path.write_text(json.dumps(abs_dataset, indent=2), encoding="utf-8")

    fits = fit_all_sweeps(
        abs_dataset["sweeps"],
        residual_threshold=args.threshold,
        min_points=args.min_points,
        square_inputs=True,
    )
    fits_path = outdir / f"{args.dataset.stem}_abs_fits.json"
    fits_path.write_text(json.dumps({"fitted_ellipses": fits}, indent=2), encoding="utf-8")

    # Plot grid of all sweeps with fits.
    fig = plot_all_sweeps(abs_dataset, ellipse_fits=fits)
    grid_path = outdir / "01_sweeps_grid.png"
    fig.savefig(grid_path, dpi=150)
    fig.clf()
    plot_entries.append(
        (
            grid_path.name,
            "`fit_all_sweeps`, `fit_ellipse_from_sweep`, `plot_all_sweeps`, `plot_ellipse_fit`",
            "Each sweep’s L² data should form an ellipse; fitted ellipses overlay points. "
            "Rejected sweeps show no (or degenerate) ellipse and a rejection label.",
        )
    )

    # Per-sweep fit + optional theoretical overlay and sampling density.
    predicted_coeffs: List[np.ndarray] = []
    observed_valid: List[dict] = []
    observed_ids: List[str] = []
    fits_by_id = {f["sweep_id"]: f for f in fits}

    for sweep in abs_dataset.get("sweeps", []):
        sid = sweep.get("id", "sweep")
        fit = fits_by_id.get(sid)
        if not fit:
            continue

        theory = None
        if anchors_true is not None:
            fixed_abs = sweep.get("fixed_lengths", [])
            theory = predict_ellipse_coefficients(
                anchors_true,
                sweep.get("fixed_anchors", []),
                fixed_abs,
                int(sweep.get("drive_anchor")),
                int(sweep.get("sensor_anchor")),
                dimensions=int(dataset.get("dimensions", 2)),
            )
            if theory is not None and fit.get("valid"):
                predicted_coeffs.append(theory)
                observed_valid.append(fit)
                observed_ids.append(sid)

        fig_fit, ax_fit = __import__("matplotlib.pyplot").pyplot.subplots(figsize=(8, 6))
        plot_ellipse_fit(
            sweep,
            fit,
            theoretical_coeffs=theory,
            align_theory_to_data=True,
            ax=ax_fit,
        )
        fit_path = outdir / f"02_fit_{sid}.png"
        fig_fit.savefig(fit_path, dpi=150)
        fig_fit.clf()
        plot_entries.append(
            (
                fit_path.name,
                "`plot_ellipse_fit`, `ellipse_geometric_params`, (optional) `predict_ellipse_coefficients`",
                "Blue points are measured sweep data (absolute). Green ellipse is the fit. "
                "If anchors were provided, red dashed ellipse is theoretical; it should closely overlap green.",
            )
        )

        fig_den, ax_den = __import__("matplotlib.pyplot").pyplot.subplots(figsize=(8, 3))
        plot_sampling_density(sweep, fit, ax=ax_den)
        den_path = outdir / f"03_sampling_{sid}.png"
        fig_den.savefig(den_path, dpi=150)
        fig_den.clf()
        plot_entries.append(
            (
                den_path.name,
                "`plot_sampling_density`, `ellipse_sampson_residuals` (via `residual_series`)",
                "Histogram shows how drive delta was sampled along the arc. "
                "Residual σ line should be low and not spike strongly in well-behaved sweeps.",
            )
        )

    # Bar comparison of observed vs predicted coefficients (if theory available).
    if predicted_coeffs:
        fig_cmp, ax_cmp = __import__("matplotlib.pyplot").pyplot.subplots(figsize=(10, 4))
        plot_residuals_comparison(observed_valid, predicted_coeffs, observed_ids, ax=ax_cmp)
        cmp_path = outdir / "04_coeff_mismatch.png"
        fig_cmp.savefig(cmp_path, dpi=150)
        fig_cmp.clf()
        plot_entries.append(
            (
                cmp_path.name,
                "`plot_residuals_comparison`, `predict_ellipse_coefficients`",
                "Bars near 0 indicate observed and theoretical ellipses match for those sweeps. "
                "Green/orange/red correspond to good/ok/bad mismatch bands.",
            )
        )

    # Plot anchors (true or solved) and optionally solve.
    if anchors_true is not None:
        fig_a, ax_a = __import__("matplotlib.pyplot").pyplot.subplots(figsize=(6, 6))
        plot_anchors_2d(anchors_true, ax=ax_a)
        a_path = outdir / "05_true_anchors.png"
        fig_a.savefig(a_path, dpi=150)
        fig_a.clf()
        plot_entries.append(
            (
                a_path.name,
                "`plot_anchors_2d`",
                "Shows the provided anchor geometry and origin. For Slideprinter you should see a triangle roughly "
                "centered above the origin.",
            )
        )

    if args.solve:
        cost_history: List[float] = []

        def _cb(xk: np.ndarray, _conv: Optional[float]) -> None:
            # Recompute cost to store history.
            from autocal.ellipse_cost import EllipseCostFunction

            cost_fn = EllipseCostFunction(
                dataset,
                residual_threshold=args.threshold,
                min_points=args.min_points,
            )
            cost_history.append(cost_fn.evaluate(xk))

        solution = solve_anchors(
            dataset,
            method=args.method,
            max_iterations=2000,
            num_restarts=4,
            residual_threshold=args.threshold,
            cost_callback=_cb,
            verbose=True,
        )
        sol_path = outdir / "solution.json"
        sol_path.write_text(
            json.dumps(
                {
                    "anchors": np.asarray(solution["anchors"]).tolist()
                    if solution["anchors"] is not None
                    else None,
                    "cost": solution["cost"],
                    "success": solution["success"],
                    "per_sweep_costs": getattr(solution.get("details"), "per_sweep_costs", None),
                },
                indent=2,
            ),
            encoding="utf-8",
        )

        anchors_sol = np.asarray(solution["anchors"], dtype=float)

        # Anchors plot with true overlay if available.
        fig_s, ax_s = __import__("matplotlib.pyplot").pyplot.subplots(figsize=(6, 6))
        plot_anchors_2d(anchors_sol, true_anchors=anchors_true, ax=ax_s)
        s_path = outdir / "06_solved_anchors.png"
        fig_s.savefig(s_path, dpi=150)
        fig_s.clf()
        plot_entries.append(
            (
                s_path.name,
                "`solve_anchors`, `EllipseCostFunction`, `plot_anchors_2d`",
                "Blue circles are solved anchors; red X (if provided) are true anchors. "
                "Dashed lines show error; these should be short if solver succeeded.",
            )
        )

        if cost_history:
            fig_c, ax_c = __import__("matplotlib.pyplot").pyplot.subplots(figsize=(8, 3))
            plot_cost_convergence(cost_history, ax=ax_c)
            c_path = outdir / "07_cost_convergence.png"
            fig_c.savefig(c_path, dpi=150)
            fig_c.clf()
            plot_entries.append(
                (
                    c_path.name,
                    "`plot_cost_convergence`, `geometry_distance`, `canonicalize_geometry`",
                    "Cost should trend downward and stabilize. A clear minimum indicates a consistent anchor fit.",
                )
            )

        # Re-inflate to solution anchors, re-fit and generate report.
        abs_dataset_sol = inflate_dataset_to_absolute(dataset, anchors=anchors_sol)
        fits_sol = fit_all_sweeps(abs_dataset_sol["sweeps"], residual_threshold=args.threshold, min_points=args.min_points, square_inputs=True)
        fits_sol_path = outdir / "best_fits.json"
        fits_sol_path.write_text(json.dumps({"fitted_ellipses": fits_sol}, indent=2), encoding="utf-8")

        rep_fig = create_calibration_report(dataset, solution, ellipse_fits=fits_sol, output_path=str(outdir / "08_calibration_report.png"))
        rep_fig.clf()
        plot_entries.append(
            (
                "08_calibration_report.png",
                "`create_calibration_report` (wraps multiple plotters) + solver outputs",
                "Multi-panel summary: anchors, example sweep fits, per-sweep costs (if present), and G-code.",
            )
        )

    write_plot_index(outdir, plot_entries)
    print(f"Wrote outputs to {outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
